---
title: "2_KOs_to_GMMs_Spain"
output: html_document
date: "2025-09-01"
---


```{r Import NGLess outputs}
library(omixerRpm)
#Import NGLess outputs
KEGGs<-read.table(file = '/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/KEGG_fpkm.profiles.txt',
                  header = TRUE, 
                  sep = "\t", 
                  row.names = 1, 
                  skip = 0, 
                  check.names = FALSE,
                  fill = TRUE,
                  quote = "")
# Clean "ko:" from rownames
rownames(KEGGs) <- sub("^ko:", "", rownames(KEGGs))
KEGGs<-KEGGs[-1,]
write.table(KEGGs, file="/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/input/KEGG_fpkm_ok.tsv", quote=FALSE, sep='\t', col.names = NA)

# Load the mapping database (v.1.09 created by me adding modules from 104 to 109)
listDB()
db <- loadDB("GMMs.v1.09")

# Run the module mapping on the loaded table.
mods <- rpm("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/input/KEGG_fpkm_ok.tsv", minimum.coverage=0.3, annotation = 1, module.db = db)

# get the name of the first predicted module
getNames(db, mods@annotation[1,]) 

GMMs<-data.frame(mods@abundance) 
names<-as.data.frame(mods@annotation)
rownames(GMMs)<-names$Module
long_names<-as.data.frame(mods@db@module.names)
GMMs$names = long_names$V2[match(rownames(GMMs),rownames(long_names))]
colnames(GMMs) <- gsub("filtered$", "", colnames(GMMs))

#Write the file to a csv to save it. 
write.csv(GMMs, file = "/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/ngless/GMMs.csv")
```

```{r Librerias phyloseq}
library(ggplot2)
library(dplyr)
library(data.table)
library(readxl)
library(phyloseq)
library(vegan)
library(microbiome)

```



```{r Tax Clean}

metadata_rif <- readRDS("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/metadata_rif.Rds")
rownames(metadata_rif)<-metadata_rif$SampleID
rownames(metadata_rif) <- gsub("/", "_", rownames(metadata_rif))
metadata_rif$SampleID<-rownames(metadata_rif)
metadata_rif <- metadata_rif %>%
  mutate(Timepoint = case_when(
    grepl("PC239|PC251|PC286|PC287", SampleID) ~ "T9plus",
    grepl("_3$", SampleID) ~ "T6",
    grepl("_2$", SampleID) ~ "T3",
    TRUE ~ "T0"
  ))
metadata_rif <- metadata_rif %>%
  mutate(Longitudinal = case_when(
    grepl("PC239|PC251|PC286|PC287", SampleID) ~ "No",
    TRUE ~ "Yes"
  ))

 otu <- subset(GMMs, select = -c(names))

 OTU = otu_table(as.matrix(otu), taxa_are_rows = TRUE)
 TAX = tax_table(as.matrix(long_names))
 SAMPLE <- sample_data(metadata_rif)
 
 #Como me daba error hetenido que especificar qué datos son qué columnas
 rownames(SAMPLE) <-metadata_rif$SampleID

 
 # merge the data
GMMs_ngless <- phyloseq(OTU, TAX, SAMPLE)


metadata<- data.frame(sample_data(GMMs_ngless)) 
data<-data.frame(sample_data(GMMs_ngless))
samples<-data$SampleID
samples <- gsub("_[0-9]", "", samples)
data$samples<-samples
# Create delta PHES
delta_df <- data
library(tidyr)
library(metadeconfoundR)
delta_wide <- pivot_wider(delta_df, 
                          id_cols = samples, 
                          names_from = Timepoint, 
                          values_from = PHES)

delta_wide$deltaPHES <- delta_wide$T6 - delta_wide$T0
# Merge deltaPHES back to the original dataframe
data <- merge(data, delta_wide[, c("samples", "deltaPHES")], by = "samples", all.x = TRUE)
rownames(data)<-data$SampleID
sample_data(GMMs_ngless)<-data


saveRDS(GMMs_ngless, file = "/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/ngless/GMMs_ngless.Rds")
```
