---
title: "2_KOs_to_GMMs_UK"
output: html_document
date: "2025-09-01"
---

# Import NGLess outputs
```{r Import NGLess outputs}
library(omixerRpm)
#Import NGLess outputs
KEGGs<-read.table(file = '/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/Secuences_bibliography/Patel_2021_09_10/KEGG_fpkm.profiles.txt',
                  header = TRUE, 
                  sep = "\t", 
                  row.names = 1, 
                  skip = 0, 
                  check.names = FALSE,
                  fill = TRUE,
                  quote = "")
# Clean "ko:" from rownames
rownames(KEGGs) <- sub("^ko:", "", rownames(KEGGs))
KEGGs<-KEGGs[-1,]
write.table(KEGGs, file="/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/Patel_analysis/inputs/KEGG_fpkm_ok.tsv", quote=FALSE, sep='\t', col.names = NA)

# Load the mapping database (v.1.08 created by me adding modules from 104 to 109)
listDB()
db <- loadDB("GMMs.v1.08")

# Run the module mapping on the loaded table.
mods <- rpm("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/Patel_analysis/inputs/KEGG_fpkm_ok.tsv", minimum.coverage=0.3, annotation = 1, module.db = db)

# get the name of the first predicted module
getNames(db, mods@annotation[1,]) 

GMMs<-data.frame(mods@abundance) 
names<-as.data.frame(mods@annotation)
rownames(GMMs)<-names$Module
long_names<-as.data.frame(mods@db@module.names)
GMMs$names = long_names$V2[match(rownames(GMMs),rownames(long_names))]
colnames(GMMs) <- gsub("filtered$", "", colnames(GMMs))

#Write the file to a csv to save it. 
write.csv(GMMs, file = "/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/Secuences_bibliography/Patel_analysis/outputs/GMMs.csv")
```

```{r Librerias phyloseq}
library(ggplot2)
library(dplyr)
library(data.table)
library(readxl)
library(phyloseq)
library(vegan)
library(microbiome)
library(tidyr)
library(metadeconfoundR)
```


# Create phyloseq from GMMs
```{r Tax Clean}

Metadata_Patel <- readRDS("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/Secuences_bibliography/Patel_analysis/outputs/Metadata_Patel.Rds")

 otu <- subset(GMMs, select = -c(names))

 OTU = otu_table(as.matrix(otu), taxa_are_rows = TRUE)
 TAX = tax_table(as.matrix(long_names))
 SAMPLE <- sample_data(Metadata_Patel)
 
 #Como me daba error hetenido que especificar qué datos son qué columnas
 rownames(SAMPLE) <-Metadata_Patel$SampleID

 
 # merge the data
GMMs_Patel <- phyloseq(OTU, TAX, SAMPLE)

metadata<- data.frame(sample_data(GMMs_Patel)) 

saveRDS(GMMs_Patel, file = "/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/Secuences_bibliography/Patel_analysis/outputs/GMMs_Patel.Rds")
```