---
title: "11_BoxPlots"
output: html_document
date: "2025-10-02"
---

#Taxa
```{r histograms taxa}
library(phyloseq)
library(ggplot2)
library(ggpubr)

ps_clr_corrected <- readRDS("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/merged/ps_clr_corrected.Rds")
ps_clr_corrected<- subset_samples(ps_clr_corrected, Timepoint %in% c("T0", "T2"))
ps_clr_corrected<- subset_samples(ps_clr_corrected, Group_cutoff_4 %in% c("R", "NR"))

# Vector of taxa IDs of interest as character vector
taxa_ids <- c(
              #Identified in both
              "ref_mOTU_v31_03701",
              #Identified via metadeconfoundR
              "ref_mOTU_v31_03698", "ref_mOTU_v31_03702", "ref_mOTU_v31_02810",
              "meta_mOTU_v31_12336"
              )

# Prune taxa using their names (rownames of tax_table)
physeq_sub <- prune_taxa(taxa_ids, ps_clr_corrected)

# Melt phyloseq object to long-format dataframe
df <- psmelt(physeq_sub)

tax<-data.frame(tax_table(ps_clr_corrected))

# Add profiled column by merging df and tax by matching OTU to rownames or appropriate id from tax:
df_with_profiled <- merge(df, tax[, c("profiled")], by.x = "OTU", by.y = "row.names", all.x = TRUE)


# Create the histogram/bar plot
ggplot(df_with_profiled, aes(x = profiled, y = Abundance, fill = Group_cutoff_4)) +
    geom_boxplot(position = position_dodge(), alpha = 0.3, outliers = FALSE) +
    labs(x = "mOTU", y = "Clr- transformed abundance") +
    theme_classic() +  
    theme(axis.text.x = element_text(angle = 90, hjust = 1))+
    geom_pwc(label = "{p.adj}{p.adj.signif}", hide.ns = TRUE, method = "wilcox_test", p.adjust.method = "BH")+
    scale_fill_manual(values = c("NR" = "#CC79A7", "R" = "#009E73"), name = "Group cutoff 4") +
    geom_jitter(aes(color = Study, , group = Group_cutoff_4), alpha =0.6,
                position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8))+
    scale_color_manual(values = c("Spain" = "#E69F00", "UK" = "#0072B2"), name = "Cohort") 
ggsave("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/merged/Figures_merged/Histograms/Taxa_all.pdf", height = 8, width = 12)

#Timepont 0
ps_T0<- subset_samples(ps_clr_corrected, Timepoint %in% c("T0"))
# Prune taxa using their names (rownames of tax_table)
physeq_sub <- prune_taxa(taxa_ids, ps_T0)

# Melt phyloseq object to long-format dataframe
df <- psmelt(physeq_sub)

tax<-data.frame(tax_table(ps_T0))

# Add profiled column by merging df and tax by matching OTU to rownames or appropriate id from tax:
df_with_profiled <- merge(df, tax[, c("profiled")], by.x = "OTU", by.y = "row.names", all.x = TRUE)


# Create the histogram/bar plot
ggplot(df_with_profiled, aes(x = profiled, y = Abundance, fill = Group_cutoff_4)) +
    geom_boxplot(position = position_dodge(), alpha = 0.3, outliers = FALSE) +
    labs(x = "mOTU", y = "Clr- transformed abundance") +
    theme_classic() +  
    theme(axis.text.x = element_text(angle = 90, hjust = 1))+
    geom_pwc(label = "{p.adj}{p.adj.signif}", hide.ns = TRUE, method = "wilcox_test", p.adjust.method = "BH")+
    scale_fill_manual(values = c("NR" = "#CC79A7", "R" = "#009E73"), name = "Group cutoff 4") +
    geom_jitter(aes(color = Study, , group = Group_cutoff_4), alpha =0.6,
                position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8))+
    scale_color_manual(values = c("Spain" = "#E69F00", "UK" = "#0072B2"), name = "Cohort") 
ggsave("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/merged/Figures_merged/Histograms/Taxa_T0.pdf", height = 8, width = 12)

#Timepont 2
ps_T2<- subset_samples(ps_clr_corrected, Timepoint %in% c("T2"))
# Prune taxa using their names (rownames of tax_table)
physeq_sub <- prune_taxa(taxa_ids, ps_T2)

# Melt phyloseq object to long-format dataframe
df <- psmelt(physeq_sub)

tax<-data.frame(tax_table(ps_T2))

# Add profiled column by merging df and tax by matching OTU to rownames or appropriate id from tax:
df_with_profiled <- merge(df, tax[, c("profiled")], by.x = "OTU", by.y = "row.names", all.x = TRUE)


# Create the histogram/bar plot
ggplot(df_with_profiled, aes(x = profiled, y = Abundance, fill = Group_cutoff_4)) +
    geom_boxplot(position = position_dodge(), alpha = 0.3, outliers = FALSE) +
    labs(x = "mOTU", y = "Clr- transformed abundance") +
    theme_classic() +  
    theme(axis.text.x = element_text(angle = 90, hjust = 1))+
    geom_pwc(label = "{p.adj}{p.adj.signif}", hide.ns = TRUE, method = "wilcox_test", p.adjust.method = "BH")+
    scale_fill_manual(values = c("NR" = "#CC79A7", "R" = "#009E73"), name = "Group cutoff 4") +
    geom_jitter(aes(color = Study, , group = Group_cutoff_4), alpha =0.6,
                position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8))+
    scale_color_manual(values = c("Spain" = "#E69F00", "UK" = "#0072B2"), name = "Cohort")  
ggsave("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/merged/Figures_merged/Histograms/Taxa_T2.pdf", height = 8, width = 12)


```

#GMM
```{r histograms GMM}
library(phyloseq)
library(ggplot2)
library(ggpubr)
library(ggbreak)

GMMs_corrected <- readRDS("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/merged/GMMs_corrected.Rds")
GMMs_corrected<- subset_samples(GMMs_corrected, Timepoint %in% c("T0", "T2"))
GMMs_corrected<- subset_samples(GMMs_corrected, Group_cutoff_4 %in% c("R", "NR"))

# Your text
text <- "MF0005 starch degradation
MF0006 lactose degradation
MF0008 maltose degradation
MF0012 trehalose degradation
MF0015 fructose degradation
MF0016 fucose degradation MF0019 rhamnose degradation MF0020 ribose degradation
MF0021 xylose degradation MF0026 tyrosine degradation I
MF0028 aspartate degradation I MF0039 methionine degradation II MF0045 cysteine degradation II
MF0049 threonine degradation I
MF0052 arginine degradation II
MF0055 arginine degradation V MF0058 lysine degradation II
MF0060 glycerol degradation I
MF0065 Bifidobacterium shunt MF0066 Entner−Doudoroff pathway
MF0069 NADH:ferredoxin oxidoreductase MF0071 pentose phosphate pathway (non−oxidative branch) MF0074 pyruvate:formate lyase MF0076 4−aminobutyrate degradation
MF0077 formate conversion MF0079 lactate consumption I
MF0082 putrescine degradation MF0085 urea degradation MF0087 acetyl−CoA to crotonyl−CoA MF0088 butyrate production I
MF0090 ethanol production I
MF0093 propionate production I
MF0094 propionate production II MF0097 homoacetogenesis MF0117 histamine degradation MF0126 4−aminobutyrate (GABA) synthesis I
MF0127 4−aminobutyrate (GABA) synthesis II MF0130 DOPAC synthesis MF0131 nitric oxide synthesis I (NO synthase) MF0132 nitric oxide synthesis II (nitrite reductase) MF0133 nitric oxide degradation I (NO dioxygenase)
MF0141 Isovaleric acid synthesis II (KADC pathway) MF0144 Inositol degradation 
MF0149 propionate degradation I"

# Extract all matches that look like MF followed by 4 digits
metadec_ids <- stringr::str_extract_all(text, "MF\\d{4}")[[1]]

# Vector of GMM IDs of interest as character vector
GMM_ids <- c(#IDentified via MaAsLin
  "MF0060", "MF0006", "MF0020",
  "MF0008", 
  "MF0071", 
  #Identified via metadeconfoundR
  metadec_ids
)

# Remove duplicates (optional)
GMM_ids <- unique(GMM_ids)

# Prune GMM using their names (rownames of tax_table)
physeq_sub <- prune_taxa(GMM_ids, GMMs_corrected)

# Melt phyloseq object to long-format dataframe
df <- psmelt(physeq_sub)


tax<-data.frame(tax_table(GMMs_corrected))
# Add V2 column by merging df and tax by matching OTU to rownames or appropriate id from tax:
df_with_V2 <- merge(df, tax[, c("V2")], by.x = "OTU", by.y = "row.names", all.x = TRUE)

# Create the histogram/bar plot
ggplot(df_with_V2, aes(x = V2, y = Abundance, fill = Group_cutoff_4)) +
  geom_boxplot(position = position_dodge(), alpha = 0.3, outliers = FALSE) +
  labs(x = "GMM", y = "Abundance") +
  theme_classic() +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_pwc(label = "{p.adj}{p.adj.signif}", hide.ns = TRUE, method = "wilcox_test", p.adjust.method = "BH")+
  scale_fill_manual(values = c("NR" = "#CC79A7", "R" = "#009E73"), name = "Group cutoff 4") +
  geom_jitter(aes(color = Study, , group = Group_cutoff_4), alpha =0.6,
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8))+
  scale_color_manual(values = c("Spain" = "#E69F00", "UK" = "#0072B2"), name = "Cohort") +
  scale_y_break(c(2.7e+6, 7.3e+6), scales = 0.5)
ggsave("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/merged/Figures_merged/Histograms/GMM_all.pdf", height = 6, width = 16)

#Timepont 0
GMMs_T0<- subset_samples(GMMs_corrected, Timepoint %in% c("T0"))
# Prune GMM using their names (rownames of tax_table)
physeq_sub <- prune_taxa(GMM_ids, GMMs_T0)

# Melt phyloseq object to long-format dataframe
df <- psmelt(physeq_sub)

tax<-data.frame(tax_table(GMMs_T0))

# Add V2 column by merging df and tax by matching OTU to rownames or appropriate id from tax:
df_with_V2<- merge(df, tax[, c("V2")], by.x = "OTU", by.y = "row.names", all.x = TRUE)


# Create the histogram/bar plot
ggplot(df_with_V2, aes(x = V2, y = Abundance, fill = Group_cutoff_4)) +
  geom_boxplot(position = position_dodge(), alpha = 0.3, outliers = FALSE) +
  labs(x = "GMM", y = "Abundance") +
  theme_classic() +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_pwc(label = "{p.adj}{p.adj.signif}", hide.ns = TRUE, method = "wilcox_test", p.adjust.method = "BH")+
  scale_fill_manual(values = c("NR" = "#CC79A7", "R" = "#009E73"), name = "Group cutoff 4") +
  geom_jitter(aes(color = Study, , group = Group_cutoff_4), alpha =0.6,
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8))+
  scale_color_manual(values = c("Spain" = "#E69F00", "UK" = "#0072B2"), name = "Cohort") +
  scale_y_break(c(2.7e+6, 7.3e+6), scales = 0.5)

ggsave("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/merged/Figures_merged/Histograms/GMM_T0.pdf", height = 6, width = 8)

#Timepont 2
GMMs_T2<- subset_samples(GMMs_corrected, Timepoint %in% c("T2"))
# Prune GMM using their names (rownames of tax_table)
physeq_sub <- prune_taxa(GMM_ids, GMMs_T2)

# Melt phyloseq object to long-format dataframe
df <- psmelt(physeq_sub)

tax<-data.frame(tax_table(GMMs_T2))

# Add V2 column by merging df and tax by matching OTU to rownames or appropriate id from tax:
df_with_V2<- merge(df, tax[, c("V2")], by.x = "OTU", by.y = "row.names", all.x = TRUE)

# Create the histogram/bar plot
ggplot(df_with_V2, aes(x = V2, y = Abundance, fill = Group_cutoff_4)) +
  geom_boxplot(position = position_dodge(), alpha = 0.3, outliers = FALSE) +
  labs(x = "GMM", y = "Abundance") +
  theme_classic() +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_pwc(label = "{p.adj}{p.adj.signif}", hide.ns = TRUE, method = "wilcox_test", p.adjust.method = "BH")+
  scale_fill_manual(values = c("NR" = "#CC79A7", "R" = "#009E73"), name = "Group cutoff 4") +
  geom_jitter(aes(color = Study, , group = Group_cutoff_4), alpha =0.6,
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8))+
  scale_color_manual(values = c("Spain" = "#E69F00", "UK" = "#0072B2"), name = "Cohort")  +
  scale_y_break(c(2.7e+6, 7.3e+6), scales = 0.5)

ggsave("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/merged/Figures_merged/Histograms/GMM_T2.pdf", height = 6, width = 8)


```

#ARG
```{r histograms ARG}
library(phyloseq)
library(ggplot2)
library(ggpubr)

ARGs_ok_corrected <- readRDS("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/merged/ARGs_ok_corrected.Rds")
ARGs_ok_corrected<- subset_samples(ARGs_ok_corrected, Timepoint %in% c("T0", "T2"))
ARGs_ok_corrected<- subset_samples(ARGs_ok_corrected, Group_cutoff_4 %in% c("R", "NR"))

# Vector of ARG IDs of interest as character vector
ARG_ids <- c(
  #Significant in both
  "ARO_3003002", 
  #Identified via metadeconfoundR
  "ARO_3004359", "ARO_3002986", "ARO_3002867", "ARO_3000498", "ARO_3000196"
)

# Prune ARG using their names (rownames of tax_table)
physeq_sub <- prune_taxa(ARG_ids, ARGs_ok_corrected)

# Melt phyloseq object to long-format dataframe
df <- psmelt(physeq_sub)


tax<-data.frame(tax_table(ARGs_ok_corrected))
# Add Best_Hit_ARO column by merging df and tax by matching OTU to rownames or appropriate id from tax:
df_with_ARO_Name <- merge(df, tax[, c("Best_Hit_ARO")], by.x = "OTU", by.y = "row.names", all.x = TRUE)

# Create the histogram/bar plot
ggplot(df_with_ARO_Name, aes(x = Best_Hit_ARO, y = Abundance, fill = Group_cutoff_4)) +
  geom_boxplot(position = position_dodge(), alpha = 0.3, outliers = FALSE) +
  labs(x = "ARGs", y = "Abundance") +
  theme_classic() +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_pwc(label = "{p.adj}{p.adj.signif}", hide.ns = TRUE, method = "wilcox_test", p.adjust.method = "BH")+
  scale_fill_manual(values = c("NR" = "#CC79A7", "R" = "#009E73"), name = "Group cutoff 4") +
  geom_jitter(aes(color = Study, , group = Group_cutoff_4), alpha =0.6,
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8))+
  scale_color_manual(values = c("Spain" = "#E69F00", "UK" = "#0072B2"), name = "Cohort") 
ggsave("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/merged/Figures_merged/Histograms/ARG_all.pdf", height = 4, width = 6)

#Timepont 0
ARGs_T0<- subset_samples(ARGs_ok_corrected, Timepoint %in% c("T0"))
# Prune ARG using their names (rownames of tax_table)
physeq_sub <- prune_taxa(ARG_ids, ARGs_T0)

# Melt phyloseq object to long-format dataframe
df <- psmelt(physeq_sub)

tax<-data.frame(tax_table(ARGs_T0))

# Add Best_Hit_ARO column by merging df and tax by matching OTU to rownames or appropriate id from tax:
df_with_ARO_Name<- merge(df, tax[, c("Best_Hit_ARO")], by.x = "OTU", by.y = "row.names", all.x = TRUE)


# Create the histogram/bar plot
ggplot(df_with_ARO_Name, aes(x = Best_Hit_ARO, y = Abundance, fill = Group_cutoff_4)) +
  geom_boxplot(position = position_dodge(), alpha = 0.3, outliers = FALSE) +
  labs(x = "ARGs", y = "Abundance") +
  theme_classic() +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_pwc(label = "{p.adj}{p.adj.signif}", hide.ns = TRUE, method = "wilcox_test", p.adjust.method = "BH")+
  scale_fill_manual(values = c("NR" = "#CC79A7", "R" = "#009E73"), name = "Group cutoff 4") +
  geom_jitter(aes(color = Study, , group = Group_cutoff_4), alpha =0.6,
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8))+
  scale_color_manual(values = c("Spain" = "#E69F00", "UK" = "#0072B2"), name = "Cohort") 
ggsave("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/merged/Figures_merged/Histograms/ARG_T0.pdf", height = 4, width = 6)

#Timepont 2
ARGs_T2<- subset_samples(ARGs_ok_corrected, Timepoint %in% c("T2"))
# Prune ARG using their names (rownames of tax_table)
physeq_sub <- prune_taxa(ARG_ids, ARGs_T2)

# Melt phyloseq object to long-format dataframe
df <- psmelt(physeq_sub)

tax<-data.frame(tax_table(ARGs_T2))

# Add Best_Hit_ARO column by merging df and tax by matching OTU to rownames or appropriate id from tax:
df_with_ARO_Name<- merge(df, tax[, c("Best_Hit_ARO")], by.x = "OTU", by.y = "row.names", all.x = TRUE)

# Create the histogram/bar plot
ggplot(df_with_ARO_Name, aes(x = Best_Hit_ARO, y = Abundance, fill = Group_cutoff_4)) +
  geom_boxplot(position = position_dodge(), alpha = 0.3, outliers = FALSE) +
  labs(x = "ARGs", y = "Abundance") +
  theme_classic() +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_pwc(label = "{p.adj}{p.adj.signif}", hide.ns = TRUE, method = "wilcox_test", p.adjust.method = "BH")+
  scale_fill_manual(values = c("NR" = "#CC79A7", "R" = "#009E73"), name = "Group cutoff 4") +
  geom_jitter(aes(color = Study, , group = Group_cutoff_4), alpha =0.6,
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8))+
  scale_color_manual(values = c("Spain" = "#E69F00", "UK" = "#0072B2"), name = "Cohort")  
ggsave("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/merged/Figures_merged/Histograms/ARG_T2.pdf", height = 4, width = 6)


```

#Metadata
```{r histograms ARG}
library(phyloseq)
library(ggplot2)
library(ggpubr)
library(tidyverse)

ps_clr_corrected <- readRDS("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/merged/ps_clr_corrected.Rds")
ps_clr_corrected<- subset_samples(ps_clr_corrected, Timepoint %in% c("T0", "T2"))
ps_clr_corrected<- subset_samples(ps_clr_corrected, Group_cutoff_4 %in% c("R", "NR"))

# Select the metadata variables of interest
vars_of_interest <- c( "Age", "PHES", "Ammonia","IL6", "Haemoglobin", "Leukocytes",                                          "Neutrophils", "Absolute_Neutrophils", "Absolute_Lymphocytes",                                        "Absolute_Monocytes", "Absolute_Eosinophils", "INR", "Fibrinogen",                                    "Urea", "Creatinine", "Total_bilirubin", "Albumin", "AST", "ALT",                                     "GGT", "Alkaline_phosphatase", "Sodium", "Potassium",                                                 "Corrected_calcium", "C_reactive_protein_CRP" )

# Reshape to long format
long_df <- metadata %>%
  pivot_longer(cols = all_of(vars_of_interest),
               names_to = "Variable",
               values_to = "Value")

# Create the box plot
ggplot(long_df, aes(x = Group_cutoff_4, y = Value, fill = Group_cutoff_4)) +
    geom_boxplot(alpha = 0.3, outlier.shape = NA) +
    geom_jitter(aes(color = Study), alpha = 0.6,
                position = position_jitter(width = 0.2)) +
    geom_pwc(label = "{p.adj}{p.adj.signif}", hide.ns = TRUE,
             method = "wilcox_test", p.adjust.method = "BH") +
    facet_wrap(~Variable, scales = "free_y") +
    scale_fill_manual(values = c("NR" = "#CC79A7", "R" = "#009E73"),
                      name = "Group cutoff 4") +
    scale_color_manual(values = c("Spain" = "#E69F00", "UK" = "#0072B2"),
                       name = "Cohort") +
    labs(x = "Group", y = "Value") +
    theme_classic() +
    theme(strip.text = element_text(face = "bold"),
          axis.text.x = element_text(angle = 0, hjust = 0.5))


ggsave("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/merged/Figures_merged/Histograms/Metadata_all.pdf", height = 4, width = 6)

#Timepont 0
ARGs_T0<- subset_samples(ARGs_ok_corrected, Timepoint %in% c("T0"))
# Prune ARG using their names (rownames of tax_table)
physeq_sub <- prune_taxa(ARG_ids, ARGs_T0)

# Melt phyloseq object to long-format dataframe
df <- psmelt(physeq_sub)

tax<-data.frame(tax_table(ARGs_T0))

# Add Best_Hit_ARO column by merging df and tax by matching OTU to rownames or appropriate id from tax:
df_with_ARO_Name<- merge(df, tax[, c("Best_Hit_ARO")], by.x = "OTU", by.y = "row.names", all.x = TRUE)


# Create the histogram/bar plot
ggplot(df_with_ARO_Name, aes(x = Best_Hit_ARO, y = Abundance, fill = Group_cutoff_4)) +
  geom_boxplot(position = position_dodge(), alpha = 0.3, outliers = FALSE) +
  labs(x = "ARGs", y = "Abundance") +
  theme_classic() +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_pwc(label = "{p.adj}{p.adj.signif}", hide.ns = TRUE, method = "wilcox_test", p.adjust.method = "BH")+
  scale_fill_manual(values = c("NR" = "#CC79A7", "R" = "#009E73"), name = "Group cutoff 4") +
  geom_jitter(aes(color = Study, , group = Group_cutoff_4), alpha =0.6,
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8))+
  scale_color_manual(values = c("Spain" = "#E69F00", "UK" = "#0072B2"), name = "Cohort")
ggsave("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/merged/Figures_merged/Histograms/ARG_T0.pdf", height = 4, width = 6)

#Timepont 2
ARGs_T2<- subset_samples(ARGs_ok_corrected, Timepoint %in% c("T2"))
# Prune ARG using their names (rownames of tax_table)
physeq_sub <- prune_taxa(ARG_ids, ARGs_T2)

# Melt phyloseq object to long-format dataframe
df <- psmelt(physeq_sub)

tax<-data.frame(tax_table(ARGs_T2))

# Add Best_Hit_ARO column by merging df and tax by matching OTU to rownames or appropriate id from tax:
df_with_ARO_Name<- merge(df, tax[, c("Best_Hit_ARO")], by.x = "OTU", by.y = "row.names", all.x = TRUE)

# Create the histogram/bar plot
ggplot(df_with_ARO_Name, aes(x = Best_Hit_ARO, y = Abundance, fill = Group_cutoff_4)) +
  geom_boxplot(position = position_dodge(), alpha = 0.3, outliers = FALSE) +
  labs(x = "ARGs", y = "Abundance") +
  theme_classic() +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_pwc(label = "{p.adj}{p.adj.signif}", hide.ns = TRUE, method = "wilcox_test", p.adjust.method = "BH")+
  scale_fill_manual(values = c("NR" = "#CC79A7", "R" = "#009E73"), name = "Group cutoff 4") +
  geom_jitter(aes(color = Study, , group = Group_cutoff_4), alpha =0.6,
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8))+
  scale_color_manual(values = c("Spain" = "#E69F00", "UK" = "#0072B2"), name = "Cohort") 
ggsave("/fast/AG_Forslund/Lola/Secuencias_INCLIVA_2024/MHE_rif/outputs/merged/Figures_merged/Histograms/ARG_T2.pdf", height = 4, width = 6)


```



###Facet_wrap GMM as example 
```{r GMM fw}
#I should run first GMM as avobe
ggplot(df_with_V2, aes(x = Group_cutoff_4, y = Abundance, fill = Group_cutoff_4)) +
    geom_boxplot(position = position_dodge(), alpha = 0.3, outlier.shape = NA) +
    labs(x = "GMM", y = "Abundance") +
    theme_classic() +  
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1, size = 6),
        axis.text.y = element_text(size = 6),
        strip.text = element_text(size = 6, face = "bold")  # <- change title size here
    ) +
    geom_pwc(label = "{p.adj}{p.adj.signif}", hide.ns = TRUE,
             method = "wilcox_test", p.adjust.method = "BH") +
    scale_fill_manual(values = c("NR" = "#CC79A7", "R" = "#009E73"),
                      name = "Group cutoff 4") +
    geom_jitter(aes(color = Study, group = Group_cutoff_4), alpha = 0.6,
                position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8)) +
    scale_color_manual(values = c("Spain" = "#E69F00", "UK" = "#0072B2"),
                       name = "Cohort") +
    facet_wrap(~V2, scales = "free_y")
```